### ISSUE TITLE
Strict Standards PHP notice

### ISSUE THREAD

**Issue by Draky50110** [matueranet/gnusocial-plugin-emoticon#1]
Hello.

Im' using PHP 5.6 and this plugin works except that it displays PHP notices about "Strict Standards".
It's not blocking but a little bit annoying.

Here are messages :
Strict Standards: Declaration of EmoticonPlugin::onPluginVersion() should be compatible with Plugin::onPluginVersion(array &$versions) in /home/draky/www/wittezaele_fr/gilles/social/local/plugins/Emoticon/EmoticonPlugin.php on line 112

Possible to correct it ?
Not sure the plugin is still developped ;)

**Comment by danships** [comment]
Thanks for reporting the issue. I do not use the plugin anymore, but it is a small fix for others to enjoy.
